stageapp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

#. means import from same directory as the urls.py file
from . import views

app_name = 'stageapp'

urlpatterns = [
    #home page
    path('', views.index, name = 'index'),
    path('bedrijfsgroepen/', views.BedrijvenGroepLijst.as_view(), name = 'lijst_bedrijfsgroepen'),
    path('bedrijvengroep_detail/<int:id>/', views.edit_bedrijvengroep, name='bedrijvengroep_detail'),
    path('delete_bedrijvengroep/<int:id>/', views.delete_bedrijvengroep, name='delete_bedrijvengroep'),
    path('nieuwe_bedrijvengroep/', views.BedrijvenGroepCreate, name='create_bedrijvengroep'),
    path('bedrijvengroep_alldata/<int:id>/', views.bedrijvengroep_alldata, name='bedrijvengroep_alldata'),
    path('vesting_detail/<int:id>/', views.edit_vesting, name='vesting_detail'),
    path('delete_vesting/<int:id>/', views.delete_vesting, name='delete_vesting'),
    path('nieuwe_vesting/<int:id>/', views.vestingCreate, name='create_vesting'),
    path('contactpersoon_detail/<int:id>/', views.edit_contactpersoon, name='contactpersoon_detail'),
    path('delete_contactpersoon/<int:id>/', views.delete_contactpersoon, name='delete_contactpersoon'),
    path('nieuwe_contactpersoon/<int:id>/', views.contactpersonencreate, name='create_contactpersoon'),
    path('contactpersonen/<int:id>/', views.contactpersonen_lijst, name='lijst_contactpersonen'),
    path('afdeling_detail/<int:id>/', views.edit_afdeling, name='afdeling_detail'),
    path('delete_afdeling/<int:id>/', views.delete_afdeling, name='delete_afdeling'),
    path('nieuwe_afdeling/<int:id>/', views.afdelingCreate, name='create_afdeling'),
    path('stageopdrachten/<int:id>/', views.stageopdrachten_lijst, name='lijst_stageopdrachten'),
    path('nieuwe_opdracht/<int:id>/', views.nieuwe_opdracht, name='nieuwe_opdracht'),
    path('edit_so/<int:so_id>/', views.edit_so, name='edit_so'),
    path('delete_so/<int:so_id>', views.delete_so, name='delete_so'),
    path('opdracht_evaluatie_assign_template/<int:id>/', views.evaluatietemplates_lijst, name='opdracht_assign_evaluatie_template'),
    path('view_evaluatie_template/<int:id>/', views.evaluatietemplate_details, name='view_evaluatie_template_details'),
    path('view_assign_evaluatie_templ_details/<int:id>/<int:id2>/', views.assign_template_details, name='assign_template_details'),
    path('opdracht_evaluatie/<int:id>/', views.view_opdracht_evaluatie, name='opdracht_evaluatie'),
    path('view_opdracht_evaluatie_criteria/<int:id>/', views.view_so_evaluatie_details, name='view_so_evaluatie_details'),
    path('edit_opdracht_evaluatie_criteria/<int:id>/', views.edit_opdracht_evaluatie_criteria, name='edit_opdracht_evaluatie_criteria'),
    path('delete_soe_criteria/<int:id>/', views.delete_soe_criteria, name='delete_soe_criteria'),
    path('view_scholengroepen/', views.ScholenGroepLijst.as_view(), name='view_scholengroepen'),
    path('edit_scholengroep/<int:id>/', views.edit_scholengroep, name='edit_scholengroep'),
    path('delete_scholengroep/<int:id>/', views.delete_scholengroep, name='delete_scholengroep'),
    path('create_scholengroep/', views.create_scholengroep, name='create_scholengroep'),
    path('view_scholen/<int:id>/', views.view_scholen, name='view_scholen'),
    path('edit_school/<int:id>/', views.edit_school, name='edit_school'),
    path('delete_school/<int:id>/', views.delete_school, name='delete_school'),
    path('create_school/<int:id>/', views.create_school, name='create_school'),
    path('view_so_calevents/<int:id>/', views.view_so_calevents,name='view_so_calevents'),
    path('edit_so_calevents/<int:id>/', views.edit_so_calevents,name='edit_so_calevents'),
    path('delete_so_calevents/<int:id>/', views.delete_so_calevents, name='delete_so_calevents'),
    path('create_so_calevents/<int:id>/', views.create_so_calevents, name='create_so_calevents'),
    path('edit_opleiding/<int:id>/', views.edit_opleiding, name='edit_opleiding'),
    path('delete_opleiding/<int:id>/', views.delete_opleiding, name='delete_opleiding'),
    path('view_opleidingen/<int:id>/', views.view_opleidingen, name='view_opleidingen'),
    path('create_opleiding/<int:id>/', views.create_opleiding, name='create_opleiding'),
    path('edit_schooljaar/<int:id>/', views.edit_schooljaar, name='edit_schooljaar'),
    path('delete_schooljaar/<int:id>/', views.delete_schooljaar, name='delete_schooljaar'),
    path('view_schooljaren/', views.view_schooljaren, name='view_schooljaren'),
    path('create_schooljaar/', views.create_schooljaar, name='create_schooljaar'),
    path('general_admin/', views.general_admin, name='general_admin'),
    path('view_klassen/<int:id>/', views.view_klassen, name='view_klassen'),
    path('edit_klas/<int:id>/', views.edit_klas, name='edit_klas'),
    path('delete_klas/<int:id>/', views.delete_klas, name='delete_klas'),
    path('create_klas/<int:id>/', views.create_klas, name='create_klas'),
    path('view_studenten/<int:id>/', views.view_studenten, name='view_studenten'),
    path('edit_student/<int:id>/<int:id2>/', views.edit_student, name='edit_student'),
    path('delete_student/<int:id>/', views.delete_student, name='delete_student'),
    path('create_student/<int:id>/', views.create_student, name='create_student'),
    #Next links are to check and edit data starting from the klasses views
    path('view_leerkrachten/<int:id>/', views.view_leerkrachten, name='view_leerkrachten'),
    path('edit_leerkracht/<int:id>/<int:id2>/', views.edit_leerkracht, name='edit_leerkracht'),
    path('delete_leerkracht/<int:id>/', views.delete_leerkracht, name='delete_leerkracht'),
    path('create_leerkracht/<int:id>/', views.create_leerkracht, name='create_leerkracht'),

    #In test
    path('create_soe_criteria/<int:id>/', views.create_soe_criteria, name='create_soe_criteria'),

    #Next links are to check and edit data starting from the scholen views
    path('view_sch_leerkrachten/<int:id>/', views.view_sch_leerkrachten, name='view_sch_leerkrachten'),
    path('edit_sch_leerkracht/<int:id>/<int:id2>/', views.edit_sch_leerkracht, name='edit_sch_leerkracht'),
    path('create_sch_leerkracht/<int:id>/', views.create_sch_leerkracht, name='create_sch_leerkracht'),



    # Werkt nog niet
    # path('opdracht_evaluatie/criteria_edit/<int:pk>', views.EvaluatieFormEditView.as_view(), name='opdracht_evaluatie_X'),



    #Test html
    path('test/', views.test, name = 'test'),

    #Niet meer in gebruik

    path('stageopdrachten/', views.stageopdrachten, name='stageopdrachten'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stagetoolproj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stageapp.urls')),
    path('users/', include('users.urls')),

]

users/urls.py
""" Defines URL patterns for users """

from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    # include default auth. urls
    path('', include('django.contrib.auth.urls')),
    # Registration Page
    path('register/', views.register, name = 'register' ),
]

stageapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import Http404, HttpResponse, HttpResponseRedirect

from django import forms

from .models import StageOpdrachten, Opleidingen, BedrijvenGroep, Bedrijfsvestingen, Afdelingen,  StageOpdrachtEvaluaties, StageOpdrachtEvaluatieDetails, Contactpersonen, EvaluatieTemplates, EvaluatieTemplateDetails, Klassen, Opleidingen, Scholen, ScholenGroep, Studenten, StageOpdrachtCalevents, Taken, Schooljaren, Leerkrachten
from .forms import StageOpdrachtenForm, OpleidingenForm, OpdrachtEvaluatieForm, OpdrachtEvaluatieDetailForm, EvaluatieFormset, BedrijvenGroepForm, VestingForm, AfdelingForm, ContactPersoonForm, OpdrachtCalEventForm, ScholenGroepForm, ScholenForm, SchooljaarForm, KlasForm, StudentForm, LeerkrachtForm

from django.contrib.auth.models import User

from django.views.generic import (FormView, ListView,DetailView, CreateView)
from django.views.generic.detail import SingleObjectMixin

from django.utils.decorators import method_decorator

from django.contrib import messages
from django.db.models import Prefetch

# Create your views here.
#Homepage
@login_required
def index(request):
    """Homepage of the Stagebegeleidings App """
    return render(request, 'stageapp/index.html')

@login_required
def test(request):
    return render(request,'stageapp/test.html')


def general_admin(request):
    """Return the page with links for general maintenance"""
    return render(request,'stageapp/general_admin.html')
@login_required
def view_opleidingen(request, id):
    """ Toon alle opleidingen van de geselecteerde school """
    """ ID = scholen id"""
    o_en = Opleidingen.objects.filter(scholen_id = id)
    s = Scholen.objects.get(id = id)
    sg = ScholenGroep.objects.get(id = s.scholengroep_id)
    context ={'o_en': o_en, 's': s, 'sg': sg}
    return render(request,'stageapp/opleidingen.html', context)


@login_required
def create_opleiding(request, id):
    """ Aanmaken nieuwe opleiding voor de geselecteerde school via Crispy Forms based on ModelForm, hence, trying to save data via the model """
    """id = scholen_id """
    s = Scholen.objects.get(id = id)
    if request.method != 'POST':
        #no data submitted
        form = OpleidingenForm()
        form.fields['scholen'].initial = id
    else:
        #POST submitted
        form = OpleidingenForm(data=request.POST)
        if form.is_valid():
            nieuwe_opleiding = form.save(commit=False)
            # Als hier bepaalde velden ingevuld moeten worden, bv de owner als het user model gebruikt wordt
            nieuwe_opleiding.created_by = request.user
            nieuwe_opleiding.save()
        return redirect('stageapp:view_opleidingen', id = s.id)
    #blank form
    context = {'form': form, 's': s}
    return render(request, 'stageapp/nieuwe_opleiding.html', context)

@login_required
def edit_opleiding(request, id):
    """ Update/edit bestaande opleiding """
    """ ID = opleidingen ID"""
    o = Opleidingen.objects.get(id=id)
    s = Scholen.objects.get(id = o.scholen_id)
    if request.method != 'POST':
        # No data submitted, create a blank form
        form = OpleidingenForm(instance = o)
    else:
        # POST submitted, process data
        form = OpleidingenForm(instance = o, data=request.POST)
        if form.is_valid():
            updated_instance = form.save(commit=False)
            # Als hier bepaalde velden ingevuld moeten worden, bv de owner als het user model gebruikt wordt
            updated_instance.last_updated_by = User.objects.get(username=request.user).username  #This returns a model instance User.objects.get(username=request.user)
            updated_instance.save()
            return redirect('stageapp:view_opleidingen', id = s.id) #Return to the view from which the request was launched

    context = {'o': o, 'form': form, 's': s}
    return render(request, 'stageapp/edit_opleiding.html', context)

@login_required
def delete_opleiding(request, id):
    """ Delete selected opleiding """
    o = Opleidingen.objects.get(id=id)
    s = Scholen.objects.get(id=o.scholen_id)

    if request.method == 'POST':
        o.delete()
        return redirect('stageapp:view_opleidingen', id = s.id )
    context = {'obj': o} #The generic name obj allows to use the delete.html file to be used for all deletion instructions
    return render(request, 'stageapp/delete.html', context)

"""Voor studenten """
@login_required
def view_studenten(request, id):
    """ Toon alle studenten van de geselecteerde school """
    """ ID = scholen id"""
    studenten = Studenten.objects.filter(scholen_id = id)
    s = Scholen.objects.get(id = id)
    sg = ScholenGroep.objects.get(id = s.scholengroep_id)
    context ={'studenten': studenten, 's': s, 'sg': sg}
    return render(request,'stageapp/view_studenten.html', context)


@login_required
def create_opleiding(request, id):
    """ Aanmaken nieuwe opleiding voor de geselecteerde school via Crispy Forms based on ModelForm, hence, trying to save data via the model """
    """id = scholen_id """
    s = Scholen.objects.get(id = id)
    if request.method != 'POST':
        #no data submitted
        form = OpleidingenForm()
        form.fields['scholen'].initial = id
    else:
        #POST submitted
        form = OpleidingenForm(data=request.POST)
        if form.is_valid():
            nieuwe_opleiding = form.save(commit=False)
            # Als hier bepaalde velden ingevuld moeten worden, bv de owner als het user model gebruikt wordt
            nieuwe_opleiding.created_by = request.user
            nieuwe_opleiding.save()
        return redirect('stageapp:view_opleidingen', id = s.id)
    #blank form
    context = {'form': form, 's': s}
    return render(request, 'stageapp/nieuwe_opleiding.html', context)

@login_required
def edit_opleiding(request, id):
    """ Update/edit bestaande opleiding """
    """ ID = opleidingen ID"""
    o = Opleidingen.objects.get(id=id)
    s = Scholen.objects.get(id = o.scholen_id)
    if request.method != 'POST':
        # No data submitted, create a blank form
        form = OpleidingenForm(instance = o)
    else:
        # POST submitted, process data
        form = OpleidingenForm(instance = o, data=request.POST)
        if form.is_valid():
            updated_instance = form.save(commit=False)
            # Als hier bepaalde velden ingevuld moeten worden, bv de owner als het user model gebruikt wordt
            updated_instance.last_updated_by = User.objects.get(username=request.user).username  #This returns a model instance User.objects.get(username=request.user)
            updated_instance.save()
            return redirect('stageapp:view_opleidingen', id = s.id) #Return to the view from which the request was launched

    context = {'o': o, 'form': form, 's': s}
    return render(request, 'stageapp/edit_opleiding.html', context)

@login_required
def delete_opleiding(request, id):
    """ Delete selected opleiding """
    o = Opleidingen.objects.get(id=id)
    s = Scholen.objects.get(id=o.scholen_id)

    if request.method == 'POST':
        o.delete()
        return redirect('stageapp:view_opleidingen', id = s.id )
    context = {'obj': o} #The generic name obj allows to use the delete.html file to be used for all deletion instructions
    return render(request, 'stageapp/delete.html', context)



#StageOpdrachten
@login_required
def stageopdrachten_lijst(request, id):
    """ Genereer een form met de stageopdrachten voor  geselecteerd bedrijfsvesting"""
    so_en =StageOpdrachten.objects.filter(bedrijfsvestingen_id=id)
    bv = Bedrijfsvestingen.objects.get(id = id)
    context = {'so_en': so_en, 'bv': bv}
    return render(request, 'stageapp/stageopdrachten_lijst.html', context)

@login_required
def nieuwe_opdracht(request, id):
    """ Aanmaken nieuwe stageopdracht voor de geselecteerde bedrijfsvesting """
    bv = Bedrijfsvestingen.objects.get(id=id)
    if request.method != 'POST':
        #no data submitted
        form = StageOpdrachtenForm()
        form.fields['bedrijfsvestingen'].initial = bv

    else:
        #POST submitted
        form = StageOpdrachtenForm(data=request.POST)
        if form.is_valid():
            nieuwe_opdracht = form.save(commit=False)
            #Als hier bepaalde velden ingevuld moeten worden, bv de owner als het user model gebruikt wordt
            #nieuwe_opdracht.bedrijfsvestingen_id = id  #We gaan dat hier niet overrulen want veld kan ingevuld worden via form.  Het wordt hierboven wel gedefault naar de bedrijfsvesting.
            nieuwe_opdracht.created_by = request.user
            nieuwe_opdracht.save()
            messages.add_message(
                request,
                messages.SUCCESS,
                'Nieuwe stageopdracht is aangemaakt.')
        return redirect('stageapp:lijst_stageopdrachten', id = id)
    #blank form
    bv = Bedrijfsvestingen.objects.get(id=id)
    context = {'form': form, 'bv': bv}
    return render(request, 'stageapp/nieuwe_opdracht.html', context)

@login_required
def edit_so(request, so_id):
    """ Update/edit bestaande stageopdracht """
    so = StageOpdrachten.objects.get(id=so_id)
    if request.method != 'POST':
        # No data submitted, create a blank form
        form = StageOpdrachtenForm(instance = so)
    else:
        # POST submitted, process data
        form = StageOpdrachtenForm(instance = so, data=request.POST)
        if form.is_valid():
            updated_opdracht = form.save(commit=False)
            # Als hier bepaalde velden ingevuld moeten worden, bv de owner als het user model gebruikt wordt
            updated_opdracht.last_updated_by = User.objects.get(username=request.user).username  #This returns a model instance User.objects.get(username=request.user)
            updated_opdracht.save()

stageapp/templates/stageapp/contactpersonen_lijst.html
{% extends 'stageapp/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Contactpersonen
{% endblock title %}


{% block page_header %}
    <h1>{{bv.bedrijfsnaam}}: Contactpersonen</h1>
{% endblock page_header %}

{% block content %}

<div class="card mb-3">
        <table>
            <th class="card-header">Voornaam - Naam</th>
            <th class="card-header">email</th>
            <th class="card-header">tel</th>
            <th class="card-header">actief</th>
            <th class="card-header"></th>
            <th class="card-header"></th>
            <div class="card-body">
                <style>
                    tr:nth-of-type(even) {
                    background-color:#B0C4DE;
                    }
                    .checked {
                        color: blue;
                            }
                </style>
                {% for contact in contactpersonen %}
                    <tr>
                        <td>{{ contact.voornaam }}  {{contact.naam}}</td>
                        <td>{{ contact.email }}</td>
                        <td>{{ contact.tel}}</td>
                        {% if contact.actief %}
                            <td><input type ="checkbox" checked disabled="disabled"></td>
                        {% else %}
                            <td><input type ="checkbox" unchecked disabled="disabled"</td>
                        {% endif %}
                        <td><small> <a href="{% url 'stageapp:contactpersoon_detail' contact.id %}"><i class="fa-solid fa-pen-to-square"></i></a></small></td>
                        <td><small><a href="{% url 'stageapp:delete_contactpersoon' contact.id %}"><i class="fas fa-trash"></i></a></small></td>
                        </tr>

                {% empty %}
                    <tr>
                        <td>Er zijn nog geen contactpersonen.</td>
                    </tr>
                {% endfor %}
                </div>
         </table>
</div>
    <hr>
        <a href="{% url 'stageapp:bedrijvengroep_alldata' bv.bedrijvengroep_id %}" class='btn btn-primary mt-3'>Naar bedrijven groep</a>
        <a href="{% url 'stageapp:create_contactpersoon' bv.id %}" class='btn btn-primary mt-3'>Toevoegen contactpersoon</a>
<div>
    <p class="pt-2">
      <a href="{% url 'stageapp:index' %}" role="button" class="btn btn-secondary w-100">Homepage</a>
    </p>
</div>

{% endblock content %}

stageapp/templates/stageapp/create_sch_leerkracht.html
{% extends 'stageapp/base.html' %}
{% load crispy_forms_tags %}

{% block page_header %}
    <h1> Aanmaak nieuwe leerkracht</h1>
    <h8>School: {{ school.school_naam }} </h8>
{% endblock page_header %}

{% block content %}
<div class="container mt-3" style="width:95%; font-size:12px">
    <form action = "{% url 'stageapp:create_sch_leerkracht' school.id %}" method='POST' class='card p-3 mt-5'>
        {% csrf_token %}
        {% crispy form %}
        <hr>
    </form>
</div>
<div>
    <p class="pt-2">
        <a href="{% url 'stageapp:view_scholen' sg.id %}" role="button" class='btn btn-primary mt-3'>Terug naar scholen overzicht</a>
        <a href="{% url 'stageapp:index' %}" role="button" class="btn btn-secondary w-100">Homepage</a>
    </p>
</div>
{% endblock content %}

stageapp/templates/stageapp/create_student.html
{% extends 'stageapp/base.html' %}
{% load crispy_forms_tags %}

{% block page_header %}
    <h1> Aanmaak nieuwe student</h1>
    <h8>School: {{ school.school_naam }} </h8>
{% endblock page_header %}

{% block content %}
<div class="container mt-3" style="width:95%; font-size:12px">
    <form action = "{% url 'stageapp:create_student' klas.id %}" method='POST' class='card p-3 mt-5'>
        {% csrf_token %}
        {% crispy form %}
        <hr>
    </form>
</div>
<div>
    <p class="pt-2">
        <a href="{% url 'stageapp:view_klassen' klas.id %}" role="button" class='btn btn-primary mt-3'>Terug naar klassen overzicht</a>
        <a href="{% url 'stageapp:index' %}" role="button" class="btn btn-secondary w-100">Homepage</a>
    </p>
</div>
{% endblock content %}

stageapp/templates/stageapp/edit_schooljaar.html
{% extends 'stageapp/base.html' %}
{% load crispy_forms_tags %}
{% load static %}


{% block page_header %}
    <link rel="stylesheet" href="{% static 'css/stagecustom.css' %}" type="text/css" />
    <h1>Update schooljaar</h1>
{% endblock page_header %}

{% block content %}
<div class="container mt-1" style="width:95%; font-size:12px">
    <form action="{% url 'stageapp:edit_schooljaar' sj.id %}" method="POST" class='card p-3 mt-1'>
        {% csrf_token %}
        {% crispy form %}
    </form>
</div>
<div>
    <p class="pt-2">
        <a href="{% url 'stageapp:view_schooljaren' %}" role="button" class='btn btn-primary mt-3'>Terug naar school jaren overzicht</a>
        <a href="{% url 'stageapp:index' %}" role="button" class="btn btn-secondary w-100">Homepage</a>
    </p>
</div>
{% endblock content %}

stageapp/templates/stageapp/edit_student.html
{% extends 'stageapp/base.html' %}
{% load crispy_forms_tags %}
{% load static %}


{% block page_header %}
    <link rel="stylesheet" href="{% static 'css/stagecustom.css' %}" type="text/css" />
    <h1>Update Student '{{ student.naam }}, {{ student.voornaam }}'</h1>
    <h8><small>Scholengroep: {{ sg.scholen_groep_naam }} > School: {{ school.school_naam }}</small></h8>
{% endblock page_header %}

{% block content %}
<div class="container mt-1" style="width:95%; font-size:12px">
    <form action="{% url 'stageapp:edit_student' student.id klas.id %}" method="POST" class='card p-3 mt-1'>
        {% csrf_token %}
        {% crispy form %}
    </form>
</div>
<div>
    <p class="pt-2">
        <a href="{% url 'stageapp:view_scholen' sg.id %}" role="button" class='btn btn-primary mt-3'>Terug naar scholen overzicht</a>
        <a href="{% url 'stageapp:view_studenten' klas.id %}" role="button" class='btn btn-primary mt-3'>Terug naar klas-studenten overzicht</a>
        <a href="{% url 'stageapp:index' %}" role="button" class="btn btn-secondary w-100">Homepage</a>
    </p>
</div>
{% endblock content %}

stageapp/templates/stageapp/scholen_lijst.html
{% extends 'stageapp/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Scholen lijst
{% endblock title %}


{% block page_header %}
    <h1>Scholen lijst</h1>
    <h8>Scholengroep: {{ sg.scholen_groep_naam }} </h8>
{% endblock page_header %}

{% block content %}

<div class="card mb-3">
        <table>
            <th class="card-header">School</th>
            <th class="card-header">Adres</th>
            <th class="card-header"></th>
            <th class="card-header"></th>
            <th class="card-header"></th>
            <th class="card-header"></th>
            <div class="card-body">
                <style>
                    tr:nth-of-type(even) {
                    background-color:#B0C4DE;
                    }
                    .checked {
                        color: blue;
                            }
                </style>
                {% for s in scholen %}
                    <tr>
                        <td><a class="text-reset" href="{{ s.get_absolute_url }}">{{ s.school_naam }}</a></td>
                        <td>{{ s.adres }}  {{s.nummer}},  {{s.postcode}} {{s.plaats}}</td>
                        <td><small> <a href="{% url 'stageapp:edit_school' s.id %}"><i class="fa-solid fa-pen-to-square"></i></a></small></td>
                        <td><small><a href="{% url 'stageapp:delete_school' s.id %}"><i class="fas fa-trash"></i></a></small></td>
                        <td><small><a href="{% url 'stageapp:view_opleidingen' s.id %}"><i class="fas fa-certificate"></i></a></small></td>
                        <td><small><a href="{% url 'stageapp:view_sch_leerkrachten' s.id %}"><i class="fa-solid fa-user-tie"></i></a></small></td>
                    </tr>

                {% empty %}
                    <tr colspan="5">
                        <td>Er zijn nog geen scholen.</td>
                    </tr>
                {% endfor %}
                </div>
         </table>
</div>
<div>
    <p class="pt-2">
        <a href="{% url 'stageapp:view_scholengroepen'%}" class='btn btn-primary mt-3'>Naar scholengroepen overzicht</a>
        <a href="{% url 'stageapp:create_school' sg.id %}" class='btn btn-primary mt-3'>Toevoegen school</a>
        <a href="{% url 'stageapp:index' %}" role="button" class="btn btn-secondary w-100">Homepage</a>
    </p>
</div>

{% endblock content %}

stageapp/templates/stageapp/studenten_lijst.html
{% extends 'stageapp/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Studenten Lijst
{% endblock title %}


{% block page_header %}
    <h1>Studenten lijst</h1>
    <h8>School: {{ school.school_naam }} > Klas: {{ klas.klas }} </h8>
{% endblock page_header %}

{% block content %}

<div class="card mb-3">
        <table>
            <th class="card-header">Naam</th>
            <th class="card-header">Voornaam</th>
            <th class="card-header">Adres</th>
            <th class="card-header">Tel</th>
            <th class="card-header">Actief</th>
            <th class="card-header"></th>
            <th class="card-header"></th>
            <div class="card-body">
                <style>
                    tr:nth-of-type(even) {
                    background-color:#B0C4DE;
                    }
                    .checked {
                        color: blue;
                            }
                </style>
                {% for s in studenten %}
                    <tr>
                        <td>{{ s.naam }}</td>
                        <td>{{ s.voornaam }}</td>
                        <td>{{ s.adres }}  {{s.nummer}},  {{s.postcode}} {{s.plaats}}</td>
                        <td>{{ s.tel }}</td>
                        {% if s.actief %}
                            <td><input type ="checkbox" checked disabled="disabled"></td>
                        {% else %}
                            <td><input type ="checkbox" unchecked disabled="disabled"</td>
                        {% endif %}
                        <td><small> <a href="{% url 'stageapp:edit_student' s.id klas.id %}"><i class="fa-solid fa-pen-to-square"></i></a></small></td>
                        <td><small><a href="{% url 'stageapp:delete_student' s.id %}"><i class="fas fa-trash"></i></a></small></td>
                    </tr>

                {% empty %}
                    <tr colspan="7">
                        <td>Er zijn nog geen studenten.</td>
                    </tr>
                {% endfor %}
                </div>
         </table>
</div>
<div>
    <p class="pt-2">
        <a href="{% url 'stageapp:view_klassen' opleiding.id %}" class='btn btn-primary mt-3'>Naar klassen overzicht</a>
        <a href="{% url 'stageapp:create_student' klas.id %}" class='btn btn-primary mt-3'>Toevoegen student</a>
        <a href="{% url 'stageapp:index' %}" role="button" class="btn btn-secondary w-100">Homepage</a>
    </p>
</div>

{% endblock content %}